// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYIN9CmMcOS8-uh6yPEiw8CE5XU3SzTvk',
    appId: '1:746524579184:web:6b9fa7a5f99f1ed0d8abb5',
    messagingSenderId: '746524579184',
    projectId: 'boardingweek',
    authDomain: 'boardingweek.firebaseapp.com',
    storageBucket: 'boardingweek.firebasestorage.app',
    measurementId: 'G-06DYWD5N8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx_IEguMiOGpDY3XSMGJu8acCkdzL7yXs',
    appId: '1:746524579184:android:72fb66b5f1ea37f6d8abb5',
    messagingSenderId: '746524579184',
    projectId: 'boardingweek',
    storageBucket: 'boardingweek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4kYJ676Rh9jmpGQQoRTpnff7Hgpnn78E',
    appId: '1:746524579184:ios:8ef0be3d4833e860d8abb5',
    messagingSenderId: '746524579184',
    projectId: 'boardingweek',
    storageBucket: 'boardingweek.firebasestorage.app',
    iosBundleId: 'com.example.bwProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4kYJ676Rh9jmpGQQoRTpnff7Hgpnn78E',
    appId: '1:746524579184:ios:8ef0be3d4833e860d8abb5',
    messagingSenderId: '746524579184',
    projectId: 'boardingweek',
    storageBucket: 'boardingweek.firebasestorage.app',
    iosBundleId: 'com.example.bwProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYIN9CmMcOS8-uh6yPEiw8CE5XU3SzTvk',
    appId: '1:746524579184:web:a65311520add8d2ad8abb5',
    messagingSenderId: '746524579184',
    projectId: 'boardingweek',
    authDomain: 'boardingweek.firebaseapp.com',
    storageBucket: 'boardingweek.firebasestorage.app',
    measurementId: 'G-MDXYJPHM2Y',
  );
}
